export const candice_results = {
    "total_count": 2306,
    "incomplete_results": false,
    "items": [
      {
        "login": "candice",
        "id": 1653995,
        "node_id": "MDQ6VXNlcjE2NTM5OTU=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1653995?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candice",
        "html_url": "https://github.com/candice",
        "followers_url": "https://api.github.com/users/candice/followers",
        "following_url": "https://api.github.com/users/candice/following{/other_user}",
        "gists_url": "https://api.github.com/users/candice/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candice/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candice/subscriptions",
        "organizations_url": "https://api.github.com/users/candice/orgs",
        "repos_url": "https://api.github.com/users/candice/repos",
        "events_url": "https://api.github.com/users/candice/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candice/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "xiajngsi",
        "id": 8209488,
        "node_id": "MDQ6VXNlcjgyMDk0ODg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8209488?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/xiajngsi",
        "html_url": "https://github.com/xiajngsi",
        "followers_url": "https://api.github.com/users/xiajngsi/followers",
        "following_url": "https://api.github.com/users/xiajngsi/following{/other_user}",
        "gists_url": "https://api.github.com/users/xiajngsi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/xiajngsi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/xiajngsi/subscriptions",
        "organizations_url": "https://api.github.com/users/xiajngsi/orgs",
        "repos_url": "https://api.github.com/users/xiajngsi/repos",
        "events_url": "https://api.github.com/users/xiajngsi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/xiajngsi/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "CBrown979",
        "id": 17838260,
        "node_id": "MDQ6VXNlcjE3ODM4MjYw",
        "avatar_url": "https://avatars.githubusercontent.com/u/17838260?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CBrown979",
        "html_url": "https://github.com/CBrown979",
        "followers_url": "https://api.github.com/users/CBrown979/followers",
        "following_url": "https://api.github.com/users/CBrown979/following{/other_user}",
        "gists_url": "https://api.github.com/users/CBrown979/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CBrown979/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CBrown979/subscriptions",
        "organizations_url": "https://api.github.com/users/CBrown979/orgs",
        "repos_url": "https://api.github.com/users/CBrown979/repos",
        "events_url": "https://api.github.com/users/CBrown979/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CBrown979/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "CandiceJoy",
        "id": 8854890,
        "node_id": "MDQ6VXNlcjg4NTQ4OTA=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8854890?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CandiceJoy",
        "html_url": "https://github.com/CandiceJoy",
        "followers_url": "https://api.github.com/users/CandiceJoy/followers",
        "following_url": "https://api.github.com/users/CandiceJoy/following{/other_user}",
        "gists_url": "https://api.github.com/users/CandiceJoy/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CandiceJoy/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CandiceJoy/subscriptions",
        "organizations_url": "https://api.github.com/users/CandiceJoy/orgs",
        "repos_url": "https://api.github.com/users/CandiceJoy/repos",
        "events_url": "https://api.github.com/users/CandiceJoy/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CandiceJoy/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "smrtsmrf",
        "id": 17756776,
        "node_id": "MDQ6VXNlcjE3NzU2Nzc2",
        "avatar_url": "https://avatars.githubusercontent.com/u/17756776?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/smrtsmrf",
        "html_url": "https://github.com/smrtsmrf",
        "followers_url": "https://api.github.com/users/smrtsmrf/followers",
        "following_url": "https://api.github.com/users/smrtsmrf/following{/other_user}",
        "gists_url": "https://api.github.com/users/smrtsmrf/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/smrtsmrf/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/smrtsmrf/subscriptions",
        "organizations_url": "https://api.github.com/users/smrtsmrf/orgs",
        "repos_url": "https://api.github.com/users/smrtsmrf/repos",
        "events_url": "https://api.github.com/users/smrtsmrf/events{/privacy}",
        "received_events_url": "https://api.github.com/users/smrtsmrf/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candicez03",
        "id": 58599808,
        "node_id": "MDQ6VXNlcjU4NTk5ODA4",
        "avatar_url": "https://avatars.githubusercontent.com/u/58599808?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candicez03",
        "html_url": "https://github.com/candicez03",
        "followers_url": "https://api.github.com/users/candicez03/followers",
        "following_url": "https://api.github.com/users/candicez03/following{/other_user}",
        "gists_url": "https://api.github.com/users/candicez03/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candicez03/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candicez03/subscriptions",
        "organizations_url": "https://api.github.com/users/candicez03/orgs",
        "repos_url": "https://api.github.com/users/candicez03/repos",
        "events_url": "https://api.github.com/users/candicez03/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candicez03/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "CandiceSG",
        "id": 9033021,
        "node_id": "MDQ6VXNlcjkwMzMwMjE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/9033021?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CandiceSG",
        "html_url": "https://github.com/CandiceSG",
        "followers_url": "https://api.github.com/users/CandiceSG/followers",
        "following_url": "https://api.github.com/users/CandiceSG/following{/other_user}",
        "gists_url": "https://api.github.com/users/CandiceSG/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CandiceSG/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CandiceSG/subscriptions",
        "organizations_url": "https://api.github.com/users/CandiceSG/orgs",
        "repos_url": "https://api.github.com/users/CandiceSG/repos",
        "events_url": "https://api.github.com/users/CandiceSG/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CandiceSG/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "cep104",
        "id": 51180851,
        "node_id": "MDQ6VXNlcjUxMTgwODUx",
        "avatar_url": "https://avatars.githubusercontent.com/u/51180851?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cep104",
        "html_url": "https://github.com/cep104",
        "followers_url": "https://api.github.com/users/cep104/followers",
        "following_url": "https://api.github.com/users/cep104/following{/other_user}",
        "gists_url": "https://api.github.com/users/cep104/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cep104/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cep104/subscriptions",
        "organizations_url": "https://api.github.com/users/cep104/orgs",
        "repos_url": "https://api.github.com/users/cep104/repos",
        "events_url": "https://api.github.com/users/cep104/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cep104/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "CandiceBrasileiro",
        "id": 96530256,
        "node_id": "U_kgDOBcDvUA",
        "avatar_url": "https://avatars.githubusercontent.com/u/96530256?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CandiceBrasileiro",
        "html_url": "https://github.com/CandiceBrasileiro",
        "followers_url": "https://api.github.com/users/CandiceBrasileiro/followers",
        "following_url": "https://api.github.com/users/CandiceBrasileiro/following{/other_user}",
        "gists_url": "https://api.github.com/users/CandiceBrasileiro/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CandiceBrasileiro/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CandiceBrasileiro/subscriptions",
        "organizations_url": "https://api.github.com/users/CandiceBrasileiro/orgs",
        "repos_url": "https://api.github.com/users/CandiceBrasileiro/repos",
        "events_url": "https://api.github.com/users/CandiceBrasileiro/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CandiceBrasileiro/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candicecz",
        "id": 25373313,
        "node_id": "MDQ6VXNlcjI1MzczMzEz",
        "avatar_url": "https://avatars.githubusercontent.com/u/25373313?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candicecz",
        "html_url": "https://github.com/candicecz",
        "followers_url": "https://api.github.com/users/candicecz/followers",
        "following_url": "https://api.github.com/users/candicecz/following{/other_user}",
        "gists_url": "https://api.github.com/users/candicecz/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candicecz/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candicecz/subscriptions",
        "organizations_url": "https://api.github.com/users/candicecz/orgs",
        "repos_url": "https://api.github.com/users/candicecz/repos",
        "events_url": "https://api.github.com/users/candicecz/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candicecz/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "AlekiChrome",
        "id": 47721785,
        "node_id": "MDQ6VXNlcjQ3NzIxNzg1",
        "avatar_url": "https://avatars.githubusercontent.com/u/47721785?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/AlekiChrome",
        "html_url": "https://github.com/AlekiChrome",
        "followers_url": "https://api.github.com/users/AlekiChrome/followers",
        "following_url": "https://api.github.com/users/AlekiChrome/following{/other_user}",
        "gists_url": "https://api.github.com/users/AlekiChrome/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/AlekiChrome/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/AlekiChrome/subscriptions",
        "organizations_url": "https://api.github.com/users/AlekiChrome/orgs",
        "repos_url": "https://api.github.com/users/AlekiChrome/repos",
        "events_url": "https://api.github.com/users/AlekiChrome/events{/privacy}",
        "received_events_url": "https://api.github.com/users/AlekiChrome/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "CandiceYT",
        "id": 23535356,
        "node_id": "MDQ6VXNlcjIzNTM1MzU2",
        "avatar_url": "https://avatars.githubusercontent.com/u/23535356?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CandiceYT",
        "html_url": "https://github.com/CandiceYT",
        "followers_url": "https://api.github.com/users/CandiceYT/followers",
        "following_url": "https://api.github.com/users/CandiceYT/following{/other_user}",
        "gists_url": "https://api.github.com/users/CandiceYT/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CandiceYT/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CandiceYT/subscriptions",
        "organizations_url": "https://api.github.com/users/CandiceYT/orgs",
        "repos_url": "https://api.github.com/users/CandiceYT/repos",
        "events_url": "https://api.github.com/users/CandiceYT/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CandiceYT/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "cndragn",
        "id": 27783329,
        "node_id": "MDQ6VXNlcjI3NzgzMzI5",
        "avatar_url": "https://avatars.githubusercontent.com/u/27783329?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cndragn",
        "html_url": "https://github.com/cndragn",
        "followers_url": "https://api.github.com/users/cndragn/followers",
        "following_url": "https://api.github.com/users/cndragn/following{/other_user}",
        "gists_url": "https://api.github.com/users/cndragn/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cndragn/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cndragn/subscriptions",
        "organizations_url": "https://api.github.com/users/cndragn/orgs",
        "repos_url": "https://api.github.com/users/cndragn/repos",
        "events_url": "https://api.github.com/users/cndragn/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cndragn/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "CandiceChuDVM",
        "id": 16929968,
        "node_id": "MDQ6VXNlcjE2OTI5OTY4",
        "avatar_url": "https://avatars.githubusercontent.com/u/16929968?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CandiceChuDVM",
        "html_url": "https://github.com/CandiceChuDVM",
        "followers_url": "https://api.github.com/users/CandiceChuDVM/followers",
        "following_url": "https://api.github.com/users/CandiceChuDVM/following{/other_user}",
        "gists_url": "https://api.github.com/users/CandiceChuDVM/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CandiceChuDVM/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CandiceChuDVM/subscriptions",
        "organizations_url": "https://api.github.com/users/CandiceChuDVM/orgs",
        "repos_url": "https://api.github.com/users/CandiceChuDVM/repos",
        "events_url": "https://api.github.com/users/CandiceChuDVM/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CandiceChuDVM/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candice2cc",
        "id": 7350766,
        "node_id": "MDQ6VXNlcjczNTA3NjY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/7350766?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candice2cc",
        "html_url": "https://github.com/candice2cc",
        "followers_url": "https://api.github.com/users/candice2cc/followers",
        "following_url": "https://api.github.com/users/candice2cc/following{/other_user}",
        "gists_url": "https://api.github.com/users/candice2cc/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candice2cc/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candice2cc/subscriptions",
        "organizations_url": "https://api.github.com/users/candice2cc/orgs",
        "repos_url": "https://api.github.com/users/candice2cc/repos",
        "events_url": "https://api.github.com/users/candice2cc/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candice2cc/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candice1027",
        "id": 11866520,
        "node_id": "MDQ6VXNlcjExODY2NTIw",
        "avatar_url": "https://avatars.githubusercontent.com/u/11866520?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candice1027",
        "html_url": "https://github.com/candice1027",
        "followers_url": "https://api.github.com/users/candice1027/followers",
        "following_url": "https://api.github.com/users/candice1027/following{/other_user}",
        "gists_url": "https://api.github.com/users/candice1027/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candice1027/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candice1027/subscriptions",
        "organizations_url": "https://api.github.com/users/candice1027/orgs",
        "repos_url": "https://api.github.com/users/candice1027/repos",
        "events_url": "https://api.github.com/users/candice1027/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candice1027/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candiceT233",
        "id": 36337519,
        "node_id": "MDQ6VXNlcjM2MzM3NTE5",
        "avatar_url": "https://avatars.githubusercontent.com/u/36337519?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candiceT233",
        "html_url": "https://github.com/candiceT233",
        "followers_url": "https://api.github.com/users/candiceT233/followers",
        "following_url": "https://api.github.com/users/candiceT233/following{/other_user}",
        "gists_url": "https://api.github.com/users/candiceT233/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candiceT233/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candiceT233/subscriptions",
        "organizations_url": "https://api.github.com/users/candiceT233/orgs",
        "repos_url": "https://api.github.com/users/candiceT233/repos",
        "events_url": "https://api.github.com/users/candiceT233/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candiceT233/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ItsJustDice",
        "id": 122986059,
        "node_id": "U_kgDOB1SeSw",
        "avatar_url": "https://avatars.githubusercontent.com/u/122986059?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ItsJustDice",
        "html_url": "https://github.com/ItsJustDice",
        "followers_url": "https://api.github.com/users/ItsJustDice/followers",
        "following_url": "https://api.github.com/users/ItsJustDice/following{/other_user}",
        "gists_url": "https://api.github.com/users/ItsJustDice/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ItsJustDice/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ItsJustDice/subscriptions",
        "organizations_url": "https://api.github.com/users/ItsJustDice/orgs",
        "repos_url": "https://api.github.com/users/ItsJustDice/repos",
        "events_url": "https://api.github.com/users/ItsJustDice/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ItsJustDice/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "capfei",
        "id": 5489711,
        "node_id": "MDQ6VXNlcjU0ODk3MTE=",
        "avatar_url": "https://avatars.githubusercontent.com/u/5489711?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/capfei",
        "html_url": "https://github.com/capfei",
        "followers_url": "https://api.github.com/users/capfei/followers",
        "following_url": "https://api.github.com/users/capfei/following{/other_user}",
        "gists_url": "https://api.github.com/users/capfei/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/capfei/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/capfei/subscriptions",
        "organizations_url": "https://api.github.com/users/capfei/orgs",
        "repos_url": "https://api.github.com/users/capfei/repos",
        "events_url": "https://api.github.com/users/capfei/events{/privacy}",
        "received_events_url": "https://api.github.com/users/capfei/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candicegjing",
        "id": 1483372,
        "node_id": "MDQ6VXNlcjE0ODMzNzI=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1483372?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candicegjing",
        "html_url": "https://github.com/candicegjing",
        "followers_url": "https://api.github.com/users/candicegjing/followers",
        "following_url": "https://api.github.com/users/candicegjing/following{/other_user}",
        "gists_url": "https://api.github.com/users/candicegjing/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candicegjing/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candicegjing/subscriptions",
        "organizations_url": "https://api.github.com/users/candicegjing/orgs",
        "repos_url": "https://api.github.com/users/candicegjing/repos",
        "events_url": "https://api.github.com/users/candicegjing/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candicegjing/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candiceywu",
        "id": 85723407,
        "node_id": "MDQ6VXNlcjg1NzIzNDA3",
        "avatar_url": "https://avatars.githubusercontent.com/u/85723407?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candiceywu",
        "html_url": "https://github.com/candiceywu",
        "followers_url": "https://api.github.com/users/candiceywu/followers",
        "following_url": "https://api.github.com/users/candiceywu/following{/other_user}",
        "gists_url": "https://api.github.com/users/candiceywu/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candiceywu/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candiceywu/subscriptions",
        "organizations_url": "https://api.github.com/users/candiceywu/orgs",
        "repos_url": "https://api.github.com/users/candiceywu/repos",
        "events_url": "https://api.github.com/users/candiceywu/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candiceywu/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candicelizabeth",
        "id": 73908878,
        "node_id": "MDQ6VXNlcjczOTA4ODc4",
        "avatar_url": "https://avatars.githubusercontent.com/u/73908878?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candicelizabeth",
        "html_url": "https://github.com/candicelizabeth",
        "followers_url": "https://api.github.com/users/candicelizabeth/followers",
        "following_url": "https://api.github.com/users/candicelizabeth/following{/other_user}",
        "gists_url": "https://api.github.com/users/candicelizabeth/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candicelizabeth/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candicelizabeth/subscriptions",
        "organizations_url": "https://api.github.com/users/candicelizabeth/orgs",
        "repos_url": "https://api.github.com/users/candicelizabeth/repos",
        "events_url": "https://api.github.com/users/candicelizabeth/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candicelizabeth/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "CandiceD17",
        "id": 47619020,
        "node_id": "MDQ6VXNlcjQ3NjE5MDIw",
        "avatar_url": "https://avatars.githubusercontent.com/u/47619020?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/CandiceD17",
        "html_url": "https://github.com/CandiceD17",
        "followers_url": "https://api.github.com/users/CandiceD17/followers",
        "following_url": "https://api.github.com/users/CandiceD17/following{/other_user}",
        "gists_url": "https://api.github.com/users/CandiceD17/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/CandiceD17/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/CandiceD17/subscriptions",
        "organizations_url": "https://api.github.com/users/CandiceD17/orgs",
        "repos_url": "https://api.github.com/users/CandiceD17/repos",
        "events_url": "https://api.github.com/users/CandiceD17/events{/privacy}",
        "received_events_url": "https://api.github.com/users/CandiceD17/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "ctnswb",
        "id": 1656556,
        "node_id": "MDQ6VXNlcjE2NTY1NTY=",
        "avatar_url": "https://avatars.githubusercontent.com/u/1656556?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/ctnswb",
        "html_url": "https://github.com/ctnswb",
        "followers_url": "https://api.github.com/users/ctnswb/followers",
        "following_url": "https://api.github.com/users/ctnswb/following{/other_user}",
        "gists_url": "https://api.github.com/users/ctnswb/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/ctnswb/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/ctnswb/subscriptions",
        "organizations_url": "https://api.github.com/users/ctnswb/orgs",
        "repos_url": "https://api.github.com/users/ctnswb/repos",
        "events_url": "https://api.github.com/users/ctnswb/events{/privacy}",
        "received_events_url": "https://api.github.com/users/ctnswb/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "cmarx2",
        "id": 46845469,
        "node_id": "MDQ6VXNlcjQ2ODQ1NDY5",
        "avatar_url": "https://avatars.githubusercontent.com/u/46845469?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cmarx2",
        "html_url": "https://github.com/cmarx2",
        "followers_url": "https://api.github.com/users/cmarx2/followers",
        "following_url": "https://api.github.com/users/cmarx2/following{/other_user}",
        "gists_url": "https://api.github.com/users/cmarx2/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cmarx2/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cmarx2/subscriptions",
        "organizations_url": "https://api.github.com/users/cmarx2/orgs",
        "repos_url": "https://api.github.com/users/cmarx2/repos",
        "events_url": "https://api.github.com/users/cmarx2/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cmarx2/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candiceCandy",
        "id": 12215054,
        "node_id": "MDQ6VXNlcjEyMjE1MDU0",
        "avatar_url": "https://avatars.githubusercontent.com/u/12215054?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candiceCandy",
        "html_url": "https://github.com/candiceCandy",
        "followers_url": "https://api.github.com/users/candiceCandy/followers",
        "following_url": "https://api.github.com/users/candiceCandy/following{/other_user}",
        "gists_url": "https://api.github.com/users/candiceCandy/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candiceCandy/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candiceCandy/subscriptions",
        "organizations_url": "https://api.github.com/users/candiceCandy/orgs",
        "repos_url": "https://api.github.com/users/candiceCandy/repos",
        "events_url": "https://api.github.com/users/candiceCandy/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candiceCandy/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candicejoyballarta",
        "id": 72430151,
        "node_id": "MDQ6VXNlcjcyNDMwMTUx",
        "avatar_url": "https://avatars.githubusercontent.com/u/72430151?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candicejoyballarta",
        "html_url": "https://github.com/candicejoyballarta",
        "followers_url": "https://api.github.com/users/candicejoyballarta/followers",
        "following_url": "https://api.github.com/users/candicejoyballarta/following{/other_user}",
        "gists_url": "https://api.github.com/users/candicejoyballarta/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candicejoyballarta/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candicejoyballarta/subscriptions",
        "organizations_url": "https://api.github.com/users/candicejoyballarta/orgs",
        "repos_url": "https://api.github.com/users/candicejoyballarta/repos",
        "events_url": "https://api.github.com/users/candicejoyballarta/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candicejoyballarta/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "Candicepan",
        "id": 48274303,
        "node_id": "MDQ6VXNlcjQ4Mjc0MzAz",
        "avatar_url": "https://avatars.githubusercontent.com/u/48274303?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Candicepan",
        "html_url": "https://github.com/Candicepan",
        "followers_url": "https://api.github.com/users/Candicepan/followers",
        "following_url": "https://api.github.com/users/Candicepan/following{/other_user}",
        "gists_url": "https://api.github.com/users/Candicepan/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Candicepan/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Candicepan/subscriptions",
        "organizations_url": "https://api.github.com/users/Candicepan/orgs",
        "repos_url": "https://api.github.com/users/Candicepan/repos",
        "events_url": "https://api.github.com/users/Candicepan/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Candicepan/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "candicecodes",
        "id": 25311374,
        "node_id": "MDQ6VXNlcjI1MzExMzc0",
        "avatar_url": "https://avatars.githubusercontent.com/u/25311374?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/candicecodes",
        "html_url": "https://github.com/candicecodes",
        "followers_url": "https://api.github.com/users/candicecodes/followers",
        "following_url": "https://api.github.com/users/candicecodes/following{/other_user}",
        "gists_url": "https://api.github.com/users/candicecodes/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/candicecodes/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/candicecodes/subscriptions",
        "organizations_url": "https://api.github.com/users/candicecodes/orgs",
        "repos_url": "https://api.github.com/users/candicecodes/repos",
        "events_url": "https://api.github.com/users/candicecodes/events{/privacy}",
        "received_events_url": "https://api.github.com/users/candicecodes/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "lexus2727",
        "id": 48888775,
        "node_id": "MDQ6VXNlcjQ4ODg4Nzc1",
        "avatar_url": "https://avatars.githubusercontent.com/u/48888775?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/lexus2727",
        "html_url": "https://github.com/lexus2727",
        "followers_url": "https://api.github.com/users/lexus2727/followers",
        "following_url": "https://api.github.com/users/lexus2727/following{/other_user}",
        "gists_url": "https://api.github.com/users/lexus2727/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/lexus2727/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/lexus2727/subscriptions",
        "organizations_url": "https://api.github.com/users/lexus2727/orgs",
        "repos_url": "https://api.github.com/users/lexus2727/repos",
        "events_url": "https://api.github.com/users/lexus2727/events{/privacy}",
        "received_events_url": "https://api.github.com/users/lexus2727/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      }
    ]
  }


  export const test_results = {
    "total_count": 122694,
    "incomplete_results": false,
    "items": [
      {
        "login": "test",
        "id": 383316,
        "node_id": "MDQ6VXNlcjM4MzMxNg==",
        "avatar_url": "https://avatars.githubusercontent.com/u/383316?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/test",
        "html_url": "https://github.com/test",
        "followers_url": "https://api.github.com/users/test/followers",
        "following_url": "https://api.github.com/users/test/following{/other_user}",
        "gists_url": "https://api.github.com/users/test/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/test/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/test/subscriptions",
        "organizations_url": "https://api.github.com/users/test/orgs",
        "repos_url": "https://api.github.com/users/test/repos",
        "events_url": "https://api.github.com/users/test/events{/privacy}",
        "received_events_url": "https://api.github.com/users/test/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "TestLeafPages",
        "id": 21636478,
        "node_id": "MDQ6VXNlcjIxNjM2NDc4",
        "avatar_url": "https://avatars.githubusercontent.com/u/21636478?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/TestLeafPages",
        "html_url": "https://github.com/TestLeafPages",
        "followers_url": "https://api.github.com/users/TestLeafPages/followers",
        "following_url": "https://api.github.com/users/TestLeafPages/following{/other_user}",
        "gists_url": "https://api.github.com/users/TestLeafPages/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/TestLeafPages/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/TestLeafPages/subscriptions",
        "organizations_url": "https://api.github.com/users/TestLeafPages/orgs",
        "repos_url": "https://api.github.com/users/TestLeafPages/repos",
        "events_url": "https://api.github.com/users/TestLeafPages/events{/privacy}",
        "received_events_url": "https://api.github.com/users/TestLeafPages/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "astaxie",
        "id": 233907,
        "node_id": "MDQ6VXNlcjIzMzkwNw==",
        "avatar_url": "https://avatars.githubusercontent.com/u/233907?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/astaxie",
        "html_url": "https://github.com/astaxie",
        "followers_url": "https://api.github.com/users/astaxie/followers",
        "following_url": "https://api.github.com/users/astaxie/following{/other_user}",
        "gists_url": "https://api.github.com/users/astaxie/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/astaxie/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/astaxie/subscriptions",
        "organizations_url": "https://api.github.com/users/astaxie/orgs",
        "repos_url": "https://api.github.com/users/astaxie/repos",
        "events_url": "https://api.github.com/users/astaxie/events{/privacy}",
        "received_events_url": "https://api.github.com/users/astaxie/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "testerSunshine",
        "id": 20162049,
        "node_id": "MDQ6VXNlcjIwMTYyMDQ5",
        "avatar_url": "https://avatars.githubusercontent.com/u/20162049?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/testerSunshine",
        "html_url": "https://github.com/testerSunshine",
        "followers_url": "https://api.github.com/users/testerSunshine/followers",
        "following_url": "https://api.github.com/users/testerSunshine/following{/other_user}",
        "gists_url": "https://api.github.com/users/testerSunshine/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/testerSunshine/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/testerSunshine/subscriptions",
        "organizations_url": "https://api.github.com/users/testerSunshine/orgs",
        "repos_url": "https://api.github.com/users/testerSunshine/repos",
        "events_url": "https://api.github.com/users/testerSunshine/events{/privacy}",
        "received_events_url": "https://api.github.com/users/testerSunshine/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "testanull",
        "id": 21060210,
        "node_id": "MDQ6VXNlcjIxMDYwMjEw",
        "avatar_url": "https://avatars.githubusercontent.com/u/21060210?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/testanull",
        "html_url": "https://github.com/testanull",
        "followers_url": "https://api.github.com/users/testanull/followers",
        "following_url": "https://api.github.com/users/testanull/following{/other_user}",
        "gists_url": "https://api.github.com/users/testanull/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/testanull/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/testanull/subscriptions",
        "organizations_url": "https://api.github.com/users/testanull/orgs",
        "repos_url": "https://api.github.com/users/testanull/repos",
        "events_url": "https://api.github.com/users/testanull/events{/privacy}",
        "received_events_url": "https://api.github.com/users/testanull/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "testing-library",
        "id": 49996085,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ5OTk2MDg1",
        "avatar_url": "https://avatars.githubusercontent.com/u/49996085?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/testing-library",
        "html_url": "https://github.com/testing-library",
        "followers_url": "https://api.github.com/users/testing-library/followers",
        "following_url": "https://api.github.com/users/testing-library/following{/other_user}",
        "gists_url": "https://api.github.com/users/testing-library/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/testing-library/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/testing-library/subscriptions",
        "organizations_url": "https://api.github.com/users/testing-library/orgs",
        "repos_url": "https://api.github.com/users/testing-library/repos",
        "events_url": "https://api.github.com/users/testing-library/events{/privacy}",
        "received_events_url": "https://api.github.com/users/testing-library/received_events",
        "type": "Organization",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "testdrivenio",
        "id": 34076873,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjM0MDc2ODcz",
        "avatar_url": "https://avatars.githubusercontent.com/u/34076873?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/testdrivenio",
        "html_url": "https://github.com/testdrivenio",
        "followers_url": "https://api.github.com/users/testdrivenio/followers",
        "following_url": "https://api.github.com/users/testdrivenio/following{/other_user}",
        "gists_url": "https://api.github.com/users/testdrivenio/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/testdrivenio/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/testdrivenio/subscriptions",
        "organizations_url": "https://api.github.com/users/testdrivenio/orgs",
        "repos_url": "https://api.github.com/users/testdrivenio/repos",
        "events_url": "https://api.github.com/users/testdrivenio/events{/privacy}",
        "received_events_url": "https://api.github.com/users/testdrivenio/received_events",
        "type": "Organization",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "testitesti22",
        "id": 80064114,
        "node_id": "MDQ6VXNlcjgwMDY0MTE0",
        "avatar_url": "https://avatars.githubusercontent.com/u/80064114?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/testitesti22",
        "html_url": "https://github.com/testitesti22",
        "followers_url": "https://api.github.com/users/testitesti22/followers",
        "following_url": "https://api.github.com/users/testitesti22/following{/other_user}",
        "gists_url": "https://api.github.com/users/testitesti22/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/testitesti22/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/testitesti22/subscriptions",
        "organizations_url": "https://api.github.com/users/testitesti22/orgs",
        "repos_url": "https://api.github.com/users/testitesti22/repos",
        "events_url": "https://api.github.com/users/testitesti22/events{/privacy}",
        "received_events_url": "https://api.github.com/users/testitesti22/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "testcontainers",
        "id": 13393021,
        "node_id": "MDEyOk9yZ2FuaXphdGlvbjEzMzkzMDIx",
        "avatar_url": "https://avatars.githubusercontent.com/u/13393021?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/testcontainers",
        "html_url": "https://github.com/testcontainers",
        "followers_url": "https://api.github.com/users/testcontainers/followers",
        "following_url": "https://api.github.com/users/testcontainers/following{/other_user}",
        "gists_url": "https://api.github.com/users/testcontainers/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/testcontainers/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/testcontainers/subscriptions",
        "organizations_url": "https://api.github.com/users/testcontainers/orgs",
        "repos_url": "https://api.github.com/users/testcontainers/repos",
        "events_url": "https://api.github.com/users/testcontainers/events{/privacy}",
        "received_events_url": "https://api.github.com/users/testcontainers/received_events",
        "type": "Organization",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "test502git",
        "id": 50769953,
        "node_id": "MDQ6VXNlcjUwNzY5OTUz",
        "avatar_url": "https://avatars.githubusercontent.com/u/50769953?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/test502git",
        "html_url": "https://github.com/test502git",
        "followers_url": "https://api.github.com/users/test502git/followers",
        "following_url": "https://api.github.com/users/test502git/following{/other_user}",
        "gists_url": "https://api.github.com/users/test502git/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/test502git/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/test502git/subscriptions",
        "organizations_url": "https://api.github.com/users/test502git/orgs",
        "repos_url": "https://api.github.com/users/test502git/repos",
        "events_url": "https://api.github.com/users/test502git/events{/privacy}",
        "received_events_url": "https://api.github.com/users/test502git/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "test123",
        "id": 27031,
        "node_id": "MDQ6VXNlcjI3MDMx",
        "avatar_url": "https://avatars.githubusercontent.com/u/27031?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/test123",
        "html_url": "https://github.com/test123",
        "followers_url": "https://api.github.com/users/test123/followers",
        "following_url": "https://api.github.com/users/test123/following{/other_user}",
        "gists_url": "https://api.github.com/users/test123/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/test123/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/test123/subscriptions",
        "organizations_url": "https://api.github.com/users/test123/orgs",
        "repos_url": "https://api.github.com/users/test123/repos",
        "events_url": "https://api.github.com/users/test123/events{/privacy}",
        "received_events_url": "https://api.github.com/users/test123/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "peeyush015",
        "id": 101388818,
        "node_id": "U_kgDOBgsSEg",
        "avatar_url": "https://avatars.githubusercontent.com/u/101388818?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/peeyush015",
        "html_url": "https://github.com/peeyush015",
        "followers_url": "https://api.github.com/users/peeyush015/followers",
        "following_url": "https://api.github.com/users/peeyush015/following{/other_user}",
        "gists_url": "https://api.github.com/users/peeyush015/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/peeyush015/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/peeyush015/subscriptions",
        "organizations_url": "https://api.github.com/users/peeyush015/orgs",
        "repos_url": "https://api.github.com/users/peeyush015/repos",
        "events_url": "https://api.github.com/users/peeyush015/events{/privacy}",
        "received_events_url": "https://api.github.com/users/peeyush015/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "testjie",
        "id": 23480729,
        "node_id": "MDQ6VXNlcjIzNDgwNzI5",
        "avatar_url": "https://avatars.githubusercontent.com/u/23480729?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/testjie",
        "html_url": "https://github.com/testjie",
        "followers_url": "https://api.github.com/users/testjie/followers",
        "following_url": "https://api.github.com/users/testjie/following{/other_user}",
        "gists_url": "https://api.github.com/users/testjie/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/testjie/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/testjie/subscriptions",
        "organizations_url": "https://api.github.com/users/testjie/orgs",
        "repos_url": "https://api.github.com/users/testjie/repos",
        "events_url": "https://api.github.com/users/testjie/events{/privacy}",
        "received_events_url": "https://api.github.com/users/testjie/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "libenhe",
        "id": 10752102,
        "node_id": "MDQ6VXNlcjEwNzUyMTAy",
        "avatar_url": "https://avatars.githubusercontent.com/u/10752102?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/libenhe",
        "html_url": "https://github.com/libenhe",
        "followers_url": "https://api.github.com/users/libenhe/followers",
        "following_url": "https://api.github.com/users/libenhe/following{/other_user}",
        "gists_url": "https://api.github.com/users/libenhe/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/libenhe/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/libenhe/subscriptions",
        "organizations_url": "https://api.github.com/users/libenhe/orgs",
        "repos_url": "https://api.github.com/users/libenhe/repos",
        "events_url": "https://api.github.com/users/libenhe/events{/privacy}",
        "received_events_url": "https://api.github.com/users/libenhe/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      },
      {
        "login": "vinta",
        "id": 652070,
        "node_id": "MDQ6VXNlcjY1MjA3MA==",
        "avatar_url": "https://avatars.githubusercontent.com/u/652070?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/vinta",
        "html_url": "https://github.com/vinta",
        "followers_url": "https://api.github.com/users/vinta/followers",
        "following_url": "https://api.github.com/users/vinta/following{/other_user}",
        "gists_url": "https://api.github.com/users/vinta/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/vinta/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/vinta/subscriptions",
        "organizations_url": "https://api.github.com/users/vinta/orgs",
        "repos_url": "https://api.github.com/users/vinta/repos",
        "events_url": "https://api.github.com/users/vinta/events{/privacy}",
        "received_events_url": "https://api.github.com/users/vinta/received_events",
        "type": "User",
        "site_admin": false,
        "score": 1.0
      }
    ]
  }
  