export const exampleUser = {
    "login": "mrsCandyBar",
    "id": 24796794,
    "node_id": "MDQ6VXNlcjI0Nzk2Nzk0",
    "avatar_url": "https://avatars.githubusercontent.com/u/24796794?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mrsCandyBar",
    "html_url": "https://github.com/mrsCandyBar",
    "followers_url": "https://api.github.com/users/mrsCandyBar/followers",
    "following_url": "https://api.github.com/users/mrsCandyBar/following{/other_user}",
    "gists_url": "https://api.github.com/users/mrsCandyBar/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mrsCandyBar/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mrsCandyBar/subscriptions",
    "organizations_url": "https://api.github.com/users/mrsCandyBar/orgs",
    "repos_url": "https://api.github.com/users/mrsCandyBar/repos",
    "events_url": "https://api.github.com/users/mrsCandyBar/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mrsCandyBar/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Candice Bär",
    "company": null,
    "blog": "",
    "location": "South Africa",
    "email": null,
    "hireable": null,
    "bio": "I'm a Front-End Developer living in Table View, South Africa.",
    "twitter_username": null,
    "public_repos": 15,
    "public_gists": 0,
    "followers": 4,
    "following": 1,
    "created_at": "2016-12-27T17:52:05Z",
    "updated_at": "2023-05-10T10:51:14Z"
  }